version: '3.8'

services:
  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENERS: INSIDE://kafka:9093
      KAFKA_LISTENER_NAME_INSIDE: INSIDE
      KAFKA_LISTENER_INTERNAL: INSIDE
      KAFKA_LISTENER_PORT: 9093
      KAFKA_LISTENER_EXTERNAL: EXTERNAL
      KAFKA_PORT: 9093
      KAFKA_LISTENER_INTERNAL_PORT: 9093
      KAFKA_LISTENER_EXTERNAL_PORT: 9093
      KAFKA_LISTENER_EXTERIOR: EXTERIOR
      KAFKA_LISTENER_NAME_EXTERNAL: EXTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ZOOKEEPER_SECURITY_PROTOCOL: PLAINTEXT
    ports:
      - "9093:9093"
    depends_on:
      - zookeeper
    networks:
      - kafka_net

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka_net

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - kafka_net

  flask:
    build: ./flask
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    depends_on:
      - kafka
      - mongo
    networks:
      - kafka_net

networks:
  kafka_net:
    driver: bridge
