version: '3.8'

services:
  kafka:
    image: confluentinc/cp-kafka:latest 
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENERS: INSIDE://kafka:9093
      KAFKA_LISTENER_NAME_INSIDE: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9093:9093"  # Exposing Kafka to the external network
    depends_on:
      - zookeeper
    networks:
      - kafka_net

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"  # Exposing Zookeeper
    networks:
      - kafka_net

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"  # Exposing MongoDB
    networks:
      - kafka_net

  flask:
    build: ./dashboard  # Change this to point to the correct folder (if 'dashboard' is correct)
    ports:
      - "5000:5000"  # Exposing Flask API on port 5000
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    depends_on:
      - kafka
      - mongo
    networks:
      - kafka_net

networks:
  kafka_net:
    driver: bridge
